package com.android.testcoroutinehiltkola.enums

import com.android.testcoroutinehiltkola.R
import com.android.testcoroutinehiltkola.model.ExpenseCategory

enum class ENUMCATEGORYEXPENSE(val category: ExpenseCategory) {

    INCOME(
        ExpenseCategory(
            R.string.income_bookkeeping,
            R.drawable.ic_attach_money_black_24dp,
            R.color.color_category_expense_pets,
            ENUMEXPENSECATEGORYTYPE.EARNING,
            R.drawable.background_expense_pets
        )
    ),
    BEAUTY(
        ExpenseCategory(
            R.string.beauty_bookkeeping,
            R.drawable.ic_beauty,
            R.color.color_category_expense_beauty,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_beauty
        )
    ),
    COFFEE(
        ExpenseCategory(
            R.string.coffee_bookkeeping,
            R.drawable.ic_coffee,
            R.color.color_category_expense_food,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_coffee
        )
    ),
    EDUCATION(
        ExpenseCategory(
            R.string.education_bookkeeping,
            R.drawable.ic_education,
            R.color.color_category_expense_education,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_education
        )
    ),
    HEALTHCARE(
        ExpenseCategory(
            R.string.healthcare_bookkeeping,
            R.drawable.ic_healthcare,
            R.color.color_category_expense_helthcare,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_healthcare
        )
    ),
    HOME(
        ExpenseCategory(
            R.string.home_bookkeeping,
            R.drawable.ic_home,
            R.color.color_category_expense_home,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_home
        )
    ),
    INVOICE(
        ExpenseCategory(
            R.string.bills_bookkeeping,
            R.drawable.ic_invoice,
            R.color.color_category_expense_bills,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_bills
        )
    ),
    KIDS(
        ExpenseCategory(
            R.string.kids_bookkeeping,
            R.drawable.ic_kids,
            R.color.color_category_expense_kids,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_kids
        )
    ),
    COMMUNICATION(
        ExpenseCategory(
            R.string.communication_bookkeeping,
            R.drawable.ic_communication,
            R.color.color_category_expense_movie,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_movie
        )
    ),
    SPORT(
        ExpenseCategory(
            R.string.sport_bookkeeping,
            R.drawable.ic_sport,
            R.color.color_category_expense_sport,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_sport
        )
    ),
    TRANSPORT(
        ExpenseCategory(
            R.string.transport_bookkeeping,
            R.drawable.ic_transport,
            R.color.color_category_expense_transport,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_transport
        )
    ),
    TRAVEL(
        ExpenseCategory(
            R.string.travel_bookkeeping,
            R.drawable.ic_travel,
            R.color.color_category_expense_travel,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_travel
        )
    ),
    TRANSFER(
        ExpenseCategory(
            R.string.transfer_bookkeeping,
            R.drawable.ic_transfer_bookeeping,
            R.color.color_envoie_argent,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_transfer
        )
    ),
    AIRTIME(
        ExpenseCategory(
            R.string.airtime_bookkeeping,
            R.drawable.icon_phone_credi_bookeeping,
            R.color.color_achat_credit,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_airtime
        )
    ),
    UNKNOWN(
        ExpenseCategory(
            R.string.unknown_bookkeeping,
            R.drawable.ic_battery_unknown,
            R.color.unknown_categorie,
            ENUMEXPENSECATEGORYTYPE.SPENDING,
            R.drawable.background_expense_unknown
        )
    )

}